jenkins:
  systemMessage: "Jenkins configured via code"
  numExecutors: 2
  mode: NORMAL

  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "password"

  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  
  # Set global environment variables here
  nodeProperties:
    - envVars:
        env:
          - key: "OTEL_INSTRUMENTATION_JENKINS_REMOTE_SPAN_ENABLED"
            value: "true"

tool:
  git:
    installations:
      - name: git
        home: /usr/bin/git
  jdk:
    installations:
      - name: "jdk8"
        home: "/usr/lib/jvm/temurin-8-jdk-arm64"
  maven:
    installations:
      - name: "M3"  # This will be the reference name used in the pipeline
        properties:
          - installSource:
              installers:
                - maven:
                    id: "3.6.3"  # Specify the desired Maven version here


unclassified:
  location:
    adminAddress: "admin@jenkins.io"
    url: "http://localhost:8080"

  openTelemetry:
    endpoint: "http://otel-collector:4317"
    serviceName: "jenkins"
    serviceNamespace: "jenkins"
    observabilityBackends:
      - jaeger:
          name: "jaeger"
          jaegerBaseUrl: "http://localhost:16686"

  globalLibraries:
    libraries:
      # This name will be used in the pipeline script
      - name: "shared-tracing-library"
        # Version or branch, empty since this isn't version-controlled
        defaultVersion: "master"
        allowVersionOverride: false
        # This is for implicitly loading the library in all pipelines.
        implicit: false
        includeInChangesets: false
        retriever:
          legacySCM:
            scm:
              fileSystem:
                path: "/var/jenkins_home/shared-libraries/shared-tracing-library"

credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              scope: SYSTEM
              id: "jenkins-user"
              description: "Jenkins user for git"
              username: "git-user"
              password: "git-pass"
